import {
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  Broadcast,
  Buildings,
  CalendarCheck,
  Clock,
  CaretCircleRight,
  CaretDown,
  CaretRight,
  ChartBar,
  ChatsCircle,
  Check,
  CreditCard,
  EnvelopeSimple,
  FacebookLogo,
  Factory,
  FileText,
  Globe,
  Headset,
  HardHat,
  Info,
  InstagramLogo,
  MagnifyingGlass,
  Minus,
  List,
  MapPin,
  MapTrifold,
  Mountains,
  Newspaper,
  Package,
  Phone,
  Play,
  Plus,
  PlugsConnected,
  Rocket,
  Receipt,
  ShareNetwork,
  Star,
  SteeringWheel,
  ShieldCheck,
  SlidersHorizontal,
  Tag,
  Truck,
  TwitterLogo,
  UserCircle,
  Users,
  Wallet,
  X,
  XLogo,
  YoutubeLogo,
  type IconWeight,
} from '@phosphor-icons/react'
import type { ComponentType } from 'react'

const iconMap: Record<string, ComponentType<{ weight?: IconWeight; className?: string }>> = {
  'map-pin': MapPin,
  phone: Phone,
  'caret-down': CaretDown,
  check: Check,
  'caret-circle-right': CaretCircleRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-down-right': ArrowDownRight,
  'arrow-up-right': ArrowUpRight,
  play: Play,
  star: Star,
  tag: Tag,
  'user-circle': UserCircle,
  'chats-circle': ChatsCircle,
  'caret-right': CaretRight,
  'envelope-simple': EnvelopeSimple,
  list: List,
  x: X,
  'twitter-logo': TwitterLogo,
  'facebook-logo': FacebookLogo,
  'instagram-logo': InstagramLogo,
  'youtube-logo': YoutubeLogo,
  'x-logo': XLogo,
  truck: Truck,
  users: Users,
  broadcast: Broadcast,
  'map-trifold': MapTrifold,
  package: Package,
  'chart-bar': ChartBar,
  'plugs-connected': PlugsConnected,
  'calendar-check': CalendarCheck,
  'file-text': FileText,
  'credit-card': CreditCard,
  factory: Factory,
  buildings: Buildings,
  'hard-hat': HardHat,
  mountains: Mountains,
  newspaper: Newspaper,
  info: Info,
  globe: Globe,
  clock: Clock,
  bell: Bell,
  receipt: Receipt,
  'share-network': ShareNetwork,
  headset: Headset,
  'steering-wheel': SteeringWheel,
  'shield-check': ShieldCheck,
  wallet: Wallet,
  'magnifying-glass': MagnifyingGlass,
  plus: Plus,
  minus: Minus,
  sliders: SlidersHorizontal,
  rocket: Rocket,
}

interface IconProps {
  name: string
  weight?: IconWeight
  className?: string
}

export function Icon({ name, weight = 'regular', className }: IconProps) {
  const Component = iconMap[name]
  if (!Component) return null
  return <Component weight={weight} className={className} />
}
